# Generated by Django 4.0.6 on 2022-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_rename_instance_id_attempt_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
