# Generated by Django 4.0.6 on 2022-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_alter_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
