# Generated by Django 4.0.6 on 2022-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_alter_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
